function funfact() {

  // Fun Fact 1
  db.collection("funfact").add({
    "fact": "Seagrass meadows, found in coastal areas, can capture and store carbon at a rate 35 times faster than tropical rainforests.",
    "category": "Environmental"
  });

  // Fun Fact 2
  db.collection("funfact").add({
    "fact": "One acre of mature trees can provide oxygen for up to 18 people per day.",
    "category": "Environmental"
  });

  // Fun Fact 3
  db.collection("funfact").add({
    "fact": "The Great Barrier Reef, the world's largest coral reef system, is home to a vast array of marine life and is visible from outer space.",
    "category": "Environmental"
  });

  // Fun Fact 4
  db.collection("funfact").add({
    "fact": "An estimated 50-80% of Earth's oxygen comes from the ocean, primarily produced by phytoplankton.",
    "category": "Environmental"
  });

  // Fun Fact 5
  db.collection("funfact").add({
    "fact": "The ozone layer, located in the Earth's stratosphere, protects life on Earth by absorbing the majority of the sun's harmful ultraviolet (UV) radiation.",
    "category": "Environmental"
  });

  // Fun Fact 6
  db.collection("funfact").add({
    "fact": "It takes about 500 years for plastic to degrade in the ocean, posing a serious threat to marine life and ecosystems.",
    "category": "Environmental"
  });

  // Fun Fact 7
  db.collection("funfact").add({
    "fact": "The average American uses around 500 plastic bags per year, contributing to plastic pollution.",
    "category": "Environmental"
  });

  // Fun Fact 8
  db.collection("funfact").add({
    "fact": "E-waste, including old electronic devices, is a significant environmental concern due to the toxic materials it contains.",
    "category": "Environmental"
  });

  // Fun Fact 9
  db.collection("funfact").add({
    "fact": "Approximately 75% of the world's fisheries are either overfished or fully exploited, impacting marine ecosystems and biodiversity.",
    "category": "Environmental"
  });

  // Fun Fact 10
  db.collection("funfact").add({
    "fact": "The production of a single hamburger requires around 660 gallons (2,500 liters) of water, contributing to water scarcity.",
    "category": "Environmental"
  });

  // Fun Fact 11
  db.collection("funfact").add({
    "fact": "The melting of Arctic ice is not only contributing to rising sea levels but also impacting polar bear habitats and ecosystems.",
    "category": "Environmental"
  });

  // Fun Fact 12
  db.collection("funfact").add({
    "fact": "Roughly 8 million metric tons of plastic waste enter the oceans each year, posing a threat to marine life and ecosystems.",
    "category": "Environmental"
  });

  // Fun Fact 13
  db.collection("funfact").add({
    "fact": "Deforestation is a significant contributor to climate change, as trees play a crucial role in absorbing carbon dioxide from the atmosphere.",
    "category": "Environmental"
  });

  // Fun Fact 14
  db.collection("funfact").add({
    "fact": "Solar energy is the most abundant and renewable source of energy on Earth, with the potential to reduce reliance on fossil fuels.",
    "category": "Environmental"
  });

  // Fun Fact 15
  db.collection("funfact").add({
    "fact": "Bees are vital pollinators, supporting the growth of fruits, vegetables, and nuts, but they are facing threats from pesticides and habitat loss.",
    "category": "Environmental"
  });

  // Fun Fact 16
  db.collection("funfact").add({
    "fact": "The average American household generates more than 4 pounds (1.8 kilograms) of trash per day, contributing to landfill issues.",
    "category": "Environmental"
  });

  // Fun Fact 17
  db.collection("funfact").add({
    "fact": "Hydropower, generated by harnessing the energy of flowing water, is a renewable energy source that produces minimal greenhouse gas emissions.",
    "category": "Environmental"
  });

  // Fun Fact 18
  db.collection("funfact").add({
    "fact": "Climate change is causing shifts in weather patterns, leading to more frequent and severe natural disasters like hurricanes, droughts, and wildfires.",
    "category": "Environmental"
  });

  // Fun fact 19
  db.collection("funfact").add({
    "fact": "Every year, an estimated 8 million metric tons of plastic enter our oceans, harming marine life and ecosystems.",
    "category": "Environmental"
  })
}

// funfact();
document.addEventListener("DOMContentLoaded", function () {
  // Đoạn mã của bạn ở đây, bao gồm cả gọi hàm funfact
  // funfact();
});

